node {
    stage('Preparation (Checking out)') {
        sh 'make'
    }

    stage('Building code') {
        sh
       
    }

    stage('Testing code') {
       
    }

    stage('Triggering job and fetching artefact after finishing') {
           
        }

    stage('Packaging and Publishing results') {
           
        }

    stage('Asking for manual approval') {
       
    }

    stage('Deployment') {
       
    }

    stage('Sending status') {
       
    }

}