stage('Preparation') {
	node {
		steps{
			git url: 'https://github.com/MNT-Lab/mntlab-pipeline.git', branch: 'mbialitski'
			//def result=checkout(git).GIT_COMMIT
		}
	}
}
stage('Building code') {
	node{
		gradle build
	}
}
stage('Testing code'){
	node{
	echo 'Testing stage'
	}
}
//stage('')
